import Image from "next/image";
import Link from "next/link";
import scholarStats from "@/data/scholarStats.json";

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

export const metadata = {
  title: "Sunaja Devi K R - Google Scholar Profile",
  description:
    "Academic publications and citations for Prof. Sunaja Devi K R, Christ University",
};

const scholarArticles = [
  {
    title:
      "ZIF-8/LDH Nanohybrids for Dye Adsorption: LDH Composition-Dependent Structure and Adsorption Performance",
    authors: "P Loganathan, C John, KR Sunaja Devi, M Priyadarshini, Sankar",
    journal: "ACS Applied Nano Materials 9 (28), 13490-13507, 2026",
    citations: 1,
  },
  {
    title:
      "Unveiling the Hydrogen Evolution Catalytic Performance of V₂AlC MAX Phase",
    authors: "C John, KR Sunaja Devi",
    journal: "Energy Technology 14 (7), 202600123, 2026",
    citations: 0,
  },
  {
    title:
      "Cr₂MoAlC₂ MAX phase and its derivative Cr₂MoC₂Tₓ MXene for supercapacitors and electrocatalytic water splitting",
    authors: "R Madhushree, KR Sunaja Devi",
    journal: "Dalton Transactions 55 (23), 9005-9022, 2026",
    citations: 0,
  },
  {
    title:
      "Fabrication of LaCoO₃/g-C₃N₅ Z-scheme photo catalyst for Allura Red dye degradation, ascorbic acid sensing and hydrogen evolution studies",
    authors: "BN Roopashree, K Gurushantha, PC Ashly, N Kottam, S Meena, GK Raghu, KR Sunaja Devi",
    journal: "Next Materials 11, 101775, 2026",
    citations: 1,
  },
  {
    title:
      "Hydrous nickel oxyhydroxide thin films on copper foil as robust electrocatalysts for alkaline oxygen evolution",
    authors: "A Shetty, P Mukherjee, K Higashimine, T Taniike, RS Vishwanath, KR Sunaja Devi",
    journal: "Catalysis Science & Technology 16 (6), 2205-2216, 2026",
    citations: 1,
  },
  {
    title:
      "Harnessing MOF Derived Frustrated Lewis Pair-CeO₂ Nano Catalyst for CO₂-Activated Soft Oxidation of Furfural to Furoic Acid",
    authors: "S Sujith, HK Meghana, M Harsha, BJ Vaishnavi, CN Mallannavar, KR Sunaja Devi, GV Shanbhag",
    journal: "Chemistry – A European Journal 32 (8), e202502616, 2026",
    citations: 0,
  },
  {
    title:
      "Keggin-Type H₅PMo₁₀V₂O₄₀ Intercalated MgAl-LDH: Structural Integrity and Bifunctional Electrocatalytic Activity",
    authors: "P Loganathan, KR Sunaja Devi, D Muthukumar",
    journal: "Inorganic Chemistry 65 (8), 4548-4568, 2026",
    citations: 2,
  },
  {
    title:
      "Utilizing Highly Reactive Lewis Pairs Generated by Oxygen Vacancies in the Cu₃Mo₂O₉ Solid Catalyst for Cycloaddition of CO₂ to 1,2-Propanediol",
    authors: "S Sujith, BJ Vaishnavi, KM Rajashekhar Vaibhava, KR Sunaja Devi, GV Shanbhag",
    journal: "Inorganic Chemistry 64 (25), 12473-12491, 2025",
    citations: 0,
  },
  {
    title:
      "Dual Purpose Behavior of Ni-PTC MOF for High Performance Supercapacitor and Water Splitting Applications",
    authors: "KR Sunaja Devi, P Loganathan, B Saravanakumar",
    journal: "Journal of Materials Chemistry A 11, 1245-1258, 2023",
    citations: 3,
  },
  {
    title:
      "Amine-Functionalized MIL-101(Fe)-NH₂@ZIF-8 Composite for Efficient Adsorption of Pb²⁺ Ions from Aqueous Solution",
    authors: "KR Sunaja Devi, S Tabassum, D Pinheiro",
    journal: "Journal of Environmental Chemical Engineering 11, 131965, 2023",
    citations: 6,
  },
  {
    title:
      "MXene@ MOF composites: converging synthesis strategies, structural features, and emerging applications",
    authors: "KR Sunaja Devi, BS Reghunath, S Mathew",
    journal: "Journal of Materials Chemistry A 11, 4520-4545, 2023",
    citations: 8,
  },
  {
    title:
      "Insights into the synergistic effect of V3S4 decorated Ti3C2 MXene as an electrode for asymmetric supercapacitor",
    authors: "KR Sunaja Devi, R Madhushree, A Jose",
    journal: "Electrochimica Acta 445, 142050, 2023",
    citations: 2,
  },
  {
    title:
      "Transition metal oxide/chalcogenide-integrated MXene heterostructures: emerging materials for supercapacitors and water splitting",
    authors: "KR Sunaja Devi, BS Reghunath, S Manickam, MY Choi",
    journal: "Chemical Engineering Journal 440, 135890, 2022",
    citations: 33,
  },
];

const interests = [
  "Materials Chemistry",
  "Metal-Organic Frameworks",
  "Nanomaterials",
  "Energy Storage",
  "Catalysis",
  "Environmental Remediation",
  "Green Chemistry",
];

export default function ScholarPage() {
  return (
    <div
      style={{ background: "#fff", minHeight: "100vh" }}
      id="scholar-page-container"
    >
      {/* Scholar-style top bar */}
      <div
        style={{
          background: "#4285f4",
          padding: "10px 24px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
          <Link
            href="/"
            style={{
              color: "#fff",
              textDecoration: "none",
              fontSize: "0.82rem",
              display: "flex",
              alignItems: "center",
              gap: "6px",
            }}
            id="back-to-main"
          >
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <polyline points="15 18 9 12 15 6" />
            </svg>
            Back to Main Site
          </Link>
        </div>
        <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
          <svg
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="#fff"
            strokeWidth="2"
          >
            <path d="M22 10v6M2 10l10-5 10 5-10 5z" />
            <path d="M6 12v5c3 3 9 3 12 0v-5" />
          </svg>
          <span
            style={{
              color: "#fff",
              fontSize: "1.15rem",
              fontWeight: 500,
              fontFamily: "'Inter', Arial, sans-serif",
            }}
          >
            Google Scholar
          </span>
          <span
            style={{
              color: "rgba(255,255,255,0.6)",
              fontSize: "0.75rem",
              marginLeft: "4px",
            }}
          >
            (Draft Preview)
          </span>
        </div>
        <div></div>
      </div>

      <div className="scholar-page">
        {/* Profile Header */}
        <div className="scholar-header" id="scholar-profile-header">
          <Image
            src={`${basePath}/images/sunaja_devi.png`}
            alt="Sunaja Devi K R"
            width={100}
            height={100}
            className="scholar-avatar"
            id="scholar-avatar"
          />
          <div className="scholar-info">
            <h1>Sunaja Devi K R</h1>
            <p className="scholar-affiliation">
              Head & Professor, Department of Chemistry, Christ (Deemed to be University),
              Bangalore
            </p>
            <p
              style={{
                fontSize: "0.85rem",
                color: "#555",
                marginBottom: "8px",
              }}
            >
              Verified email at christuniversity.in &bull;{" "}
              <a
                href="https://scholar.google.com/citations?user=HmOcEpIAAAAJ&hl=en"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "#1a73e8", fontWeight: 500 }}
                id="official-scholar-link"
              >
                Google Scholar Profile ↗
              </a>
              {" "}&bull;{" "}
              <a
                href="https://www.sciencedirect.com/author/55450509500/kalathiparambil-rajendra-pai-sunajadevi"
                target="_blank"
                rel="noopener noreferrer"
                style={{ color: "#1a73e8", fontWeight: 500 }}
                id="official-scopus-link"
              >
                Scopus Profile ↗
              </a>
            </p>
            <div className="scholar-interests">
              {interests.map((interest, idx) => (
                <span
                  key={idx}
                  className="scholar-interest-tag"
                  id={`interest-${idx}`}
                >
                  {interest}
                  {idx < interests.length - 1 && " · "}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* Citation Stats */}
        <div className="scholar-stats" id="scholar-stats">
          <div className="scholar-stat">
            <span className="scholar-stat-label">&nbsp;</span>
            <span className="scholar-stat-label" style={{ fontWeight: 600 }}>
              &nbsp;
            </span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-label">All</span>
            <span className="scholar-stat-label" style={{ fontWeight: 600 }}>
              Since 2021
            </span>
          </div>
          <div className="scholar-stat" style={{ borderRight: "none" }}></div>
        </div>

        <div
          className="scholar-stats"
          style={{ marginTop: "-13px" }}
          id="scholar-citation-table"
        >
          <div className="scholar-stat">
            <span className="scholar-stat-label">Citations</span>
            <span></span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-value">{scholarStats.citations}</span>
            <span></span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-value">
              {scholarStats.citationsSince2021}
            </span>
            <span></span>
          </div>
        </div>

        <div
          className="scholar-stats"
          style={{ marginTop: "-13px" }}
          id="scholar-hindex"
        >
          <div className="scholar-stat">
            <span className="scholar-stat-label">h-index</span>
            <span></span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-value">{scholarStats.hIndex}</span>
            <span></span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-value">{scholarStats.hIndexSince2021}</span>
            <span></span>
          </div>
        </div>

        <div
          className="scholar-stats"
          style={{ marginTop: "-13px", marginBottom: "24px" }}
          id="scholar-i10index"
        >
          <div className="scholar-stat">
            <span className="scholar-stat-label">i10-index</span>
            <span></span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-value">{scholarStats.i10Index}</span>
            <span></span>
          </div>
          <div className="scholar-stat">
            <span className="scholar-stat-value">{scholarStats.i10IndexSince2021}</span>
            <span></span>
          </div>
        </div>

        {/* Articles */}
        <div className="scholar-articles" id="scholar-articles-section">
          <h2>Articles</h2>
          {scholarArticles.map((article, idx) => (
            <div className="scholar-article" key={idx} id={`scholar-article-${idx}`}>
              <span className="scholar-article-title">{article.title}</span>
              <p className="scholar-article-authors">{article.authors}</p>
              <p className="scholar-article-journal">{article.journal}</p>
              <p className="scholar-article-citations">
                Cited by {article.citations}
              </p>
            </div>
          ))}
        </div>

        {/* Draft Notice */}
        <div
          style={{
            marginTop: "40px",
            padding: "20px",
            background: "#fff3cd",
            borderRadius: "8px",
            border: "1px solid #ffc107",
            textAlign: "center",
          }}
          id="draft-notice"
        >
          <p
            style={{ fontSize: "0.88rem", color: "#856404", fontWeight: 500 }}
          >
            ⚠️ This is a draft preview of the Google Scholar profile. The data
            shown here is representative and may not reflect the most current
            publication metrics.
          </p>
          <p style={{ fontSize: "0.82rem", color: "#856404", marginTop: "6px" }}>
            Visit the{" "}
            <a
              href="https://scholar.google.com/citations?user=HmOcEpIAAAAJ&hl=en"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "#1a73e8", fontWeight: 600 }}
            >
              official Google Scholar profile
            </a>{" "}
            for the latest data.
          </p>
        </div>
      </div>
    </div>
  );
}
